name: Run Python Script Every Half Hour

on:
  schedule:
    - cron: '0,30 * * * *'  # Runs every half hour

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python version available

      - name: Run Script
        run: |
          python outplay_automation.py  # Run your Python script
